dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev
  otelcol_version: 0.72.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.72.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/jaegerexporter v0.72.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/zipkinexporter v0.72.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.72.0
  - gomod: github.com/eojeah/otelcol/collector/processor/spanattributeprocessor v0.72.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.72.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver v0.72.0