receivers:
  otlp:
    protocols:
      grpc:
  zipkin:

processors:

exporters:
  logging:
    verbosity: detailed
  jaeger:
    endpoint: localhost:14250
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp, zipkin]
      processors: []
      exporters: [logging, jaeger]