receivers:
  otlp:
    protocols:
      grpc:
  zipkin:

processors:
  spanattributeprocessor:
    os_type: "linux"

exporters:
  logging:
    verbosity: detailed
  jaeger:
    endpoint: localhost:14250
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp, zipkin]
      processors: [spanattributeprocessor]
      exporters: [logging, jaeger]
