receivers:
  otlp:
    protocols:
      grpc:
  zipkin:
    endpoint: 0.0.0.0:9911

processors:
  spanattributeprocessor:
    os_type: "linux"

exporters:
  logging:
    verbosity: detailed
  jaeger:
    endpoint: localhost:14250
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [zipkin]
      processors: [spanattributeprocessor]
      exporters: [logging]
